### ISSUE TITLE
Change error message

### ISSUE THREAD

**Issue by matiasandina** [RedSweatshirt/FEDWatcher#12]
https://github.com/RedSweatshirt/FEDWatcher/blob/955250a4ccc111117a6684657c73cb67a3ba4d98/fedwatcher/src/fedwatcher.py#L66

I think this can be changed to something like "Could not connect to any port" or something that explains better what happened.
Not sure about what the user should do if met with this error, it would be neat if the error can suggest that too.

**Comment by RedSweatshirt** [comment]
Made error messages more detailed.
