### ISSUE TITLE
Parametrize and/or properly comment

### ISSUE THREAD

**Issue by matiasandina** [RedSweatshirt/FEDWatcher#13]
These lines have hardcoded values, we should probably make clear that they come from how `FED_library` is handling the data line. I think we should parametrize these, or at the very least comment about what's the expected structure and reference properly where things are on the other library.

https://github.com/RedSweatshirt/FEDWatcher/blob/955250a4ccc111117a6684657c73cb67a3ba4d98/fedwatcher/src/fedwatcher.py#L116-L118

**Comment by RedSweatshirt** [comment]
Documented in code. Can't really parametrize, as it's hardcoded in FED3_Library.
