### ISSUE TITLE
Handle data streams

### ISSUE THREAD

**Issue by matiasandina** [RedSweatshirt/FEDWatcher#4]
- [x] Create `data.frames` as stream of data that will grow line by line
- [x] Add the RPi timestamp as a new column `yyyy-mm-dd HH:MM:SS`
- [x] Split data streams using FED device number instead of port
- [x] Write the `data.frames` to file every 100 (?) iteration

**Comment by RedSweatshirt** [comment]
Represented by dictionary of fed device_number to list of dictionaries representing data line by line, from old to new. Cast into pandas dataframe for saving to csv.
